import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "material-symbols";
import "./globals.css";
import Image from "next/image";
import style from "./layout.module.scss";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={style.header}>
          <Link href="/">
            <Image src="/logo.png" alt="logo" width={50} height={50} />
          </Link>
          <h3>Weather App</h3>
        </header>
        {children}
      </body>
    </html>
  );
}
